### ISSUE TITLE
grey EduPack screen

### ISSUE THREAD

**Issue by paul-triebkorn** [BrainModes/EduPack#6]
I downloaded TVB 1.5 + EduPack from github.
Starting TVB in my browser (both Chrome and Safari), than on project or simulator page EduPack pops-up but without any content, text or buttons. 

Any thoughts why ? 
![bildschirmfoto 2016-10-20 um 22 13 49](https://cloud.githubusercontent.com/assets/17988519/19576628/ee8ec19c-9713-11e6-9580-7cee333b204e.png)

**Comment by danielberlin** [comment]
Thank you for reporting, this is fixed now.
